/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.william.quiz;

import java.awt.Color;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author William
 */
public class JuegoQuiz extends javax.swing.JFrame {
    // Cambiar numeros por preguntas y respuestas, cada {} dentro de respuestas equivale a 3 respuestas para cada pregunta
    String [] preguntas = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"};
    String [][] respuestas = {{"1", "2", "3"}, {"4", "5", "6"}, {"7", "8", "9"}, {"10", "11", "12"}, {"13", "14", "15"}, {"16", "17", "18"}, {"19", "20", "21"}
    , {"22", "22", "24"}, {"25", "26", "27"}, {"28", "29", "30"}, {"31", "32", "33"}, {"34", "35", "36"}, {"37", "38", "39"}, {"40", "41", "42"}, {"43", "44", "45"}, 
    {"46", "47", "48"}, {"49", "50", "51"}, {"52", "53", "54"}, {"55", "56", "57"}, {"58", "59", "60"}};
    
    Random r = new Random();
    
    
    int index = r.nextInt(preguntas.length);
    int correctas = 0; //contador de respuestas correctas
    int equivocadas = 0; //contador de respuestas equivocadas
    float media = 0;
    float varianza = 0;
    
    ButtonGroup bg = new ButtonGroup();
    
    
    /**
     * Creates new form JuegoQuiz
     */
    public JuegoQuiz() {
        initComponents();
        
        bg.add(jrbRespuesta1);
        bg.add(jrbRespuesta2);
        bg.add(jrbRespuesta3);
        
        btnSiguienteActionPerformed(null);
        
    }
    
    public void getSelectedOption(JRadioButton jrbtn ){ //Obtener respuesta seleccionada
        //Comprobar las respuestas correctas
        if(jrbtn.getText().equals(respuestas[index][2])){ 
            correctas++;
        }else{
            equivocadas++;
        }
        index++;
        enableRadioButtons(false);
    }
    
    public void enableRadioButtons(boolean si_no){ //Elegir una respuesta luego de responder una pregunta
        jrbRespuesta1.setEnabled(si_no);
        jrbRespuesta2.setEnabled(si_no);
        jrbRespuesta3.setEnabled(si_no);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbPregunta = new javax.swing.JLabel();
        jrbRespuesta1 = new javax.swing.JRadioButton();
        jrbRespuesta2 = new javax.swing.JRadioButton();
        jrbRespuesta3 = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbPregunta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPregunta.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jrbRespuesta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbRespuesta1.setText("jRadioButton1");
        jrbRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRespuesta1ActionPerformed(evt);
            }
        });

        jrbRespuesta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbRespuesta2.setText("jRadioButton2");
        jrbRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRespuesta2ActionPerformed(evt);
            }
        });

        jrbRespuesta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbRespuesta3.setText("jRadioButton3");
        jrbRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRespuesta3ActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jrbRespuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbRespuesta2)
                .addGap(138, 138, 138)
                .addComponent(jrbRespuesta3)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbRespuesta1)
                    .addComponent(jrbRespuesta2)
                    .addComponent(jrbRespuesta3))
                .addGap(115, 115, 115)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRespuesta1ActionPerformed
       getSelectedOption(jrbRespuesta1);
       
        
    }//GEN-LAST:event_jrbRespuesta1ActionPerformed

    private void jrbRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRespuesta2ActionPerformed
        getSelectedOption(jrbRespuesta2);
    }//GEN-LAST:event_jrbRespuesta2ActionPerformed

    private void jrbRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRespuesta3ActionPerformed
        getSelectedOption(jrbRespuesta3);
    }//GEN-LAST:event_jrbRespuesta3ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        if(btnSiguiente.getText().equals("Reiniciar")){ //reiniciar al finalizar el juego 
            btnSiguiente.setText("Siguiente");
            index = 0;
            correctas = 0;
            jPanel1.setBackground(Color.lightGray);
        }
        
        if(index == preguntas.length){
            //calculo de media
            int sumam = 0;
            int sumav = 0;
            
            for(int i=0; i<preguntas.length; i++){
                sumam += Integer.parseInt( preguntas[i]);
            }
            media = sumam / preguntas.length;
            
            //calculo de varianza
            double sum=0;
            for(int i=0; i<preguntas.length; i++){
                sumav+=Math.pow(Double.parseDouble(preguntas[i]), 2);
            }
            varianza = (float) (sumav / preguntas.length - Math.pow(media, 2));
            
            
        
            
            //Pantalla final del juego
            jlbPregunta.setText("Acertaste "+correctas+" / " +preguntas.length + " preguntas!");
            if(correctas > (float) preguntas.length / 2){
                jPanel1.setBackground(Color.green);
                
            }else{
                jPanel1.setBackground(Color.red);
            }
            
            btnSiguiente.setText("Reiniciar");
        }
        
        else{
            
            enableRadioButtons(true);
            jlbPregunta.setText(preguntas[index]);
            jrbRespuesta1.setText(respuestas[index][0]);
            jrbRespuesta2.setText(respuestas[index][1]);
            jrbRespuesta3.setText(respuestas[index][2]);
        
            if(index == preguntas.length){ //fin del juego
                btnSiguiente.setText("Teminar");
            }
            
        }
        
        bg.clearSelection(); //Limpiar respuestas
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbPregunta;
    private javax.swing.JRadioButton jrbRespuesta1;
    private javax.swing.JRadioButton jrbRespuesta2;
    private javax.swing.JRadioButton jrbRespuesta3;
    // End of variables declaration//GEN-END:variables
}
